title: Nirav Bariya
logo: /assets/images/profile_repo.png
description: This repository contains python scripts and other files related to Instacart Sales and Customer Analysis Project.
show_downloads: false
theme: jekyll-theme-minimal
